### ISSUE TITLE
Rule Change Suggestion - Arrow Function should not return assignent.

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/eslint-config-mx#16]
I was working today and did something like this: 

```
ref={(ref) => this.myRangeSelector = ref}
```

This threw an eslint Arrow function should not return assignment warning. I was curious what everyone thinks of this rule and if we could 😲 kill 😲  it

**Comment by rachelpipkin** [comment]
🔥  it!

**Comment by bsbeeks** [comment]
The problem with that arrow method is that you are assigning `ref` to `this.myRangeSelector` AND returning that assignment. I think this is more of a problem with not using curly brackets, than it is with the eslint rule. By including the curly brackets the arrow method doesn't return the last declaration. That being said, I think this will throw a different eslint error where it wants the content inside the curly brackets to be on it's own line.

``` javascript
ref={(ref) => { this.myRangeSelector = ref }}
```

**Comment by lukeschunk** [comment]
yeah - in the PR i ended up using this - basically for the reasons you said: 

```
          ref={(ref) => {
            this.rangeSelectorRef = ref;
          }}
```

what's the biggest risk with 'returning assignment'?

**Comment by paniclater** [comment]
I actually like returning the assignment by default. I think the cases in which a function that previously returned undefined that now returns a value that are risky are limited to functions that rely on values returned to signify 'truthiness'.

Returning a value by default (even if it isn't needed by for the application) also makes functions much easier to test.

I don't think in this example returning the assignment will cause a problem.

**Comment by jtanner** [comment]
Let's get rid of it 👍

**Comment by jtanner** [comment]
If we don't get rid of it I've found that the following works:

``` javascript
ref={ref => (this.myRangeSelector = ref)}
```

**Comment by lukeschunk** [comment]
i'll put up a PR. and you're right @jtanner I just discovered that as well

**Comment by paniclater** [comment]
I prefer without the parentheses, but this isn't an issue I care that deeply about :)
